import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


const Home: NextPage = () => {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/faviacon.ico" />
    </Head>
    <Header />
    <main className=" flex flex-col text-center m-auto w-96">
      <h1 className="mt-40 text-3xl">O melhor jeito de comprar o que você ama!</h1>
      <p className="text-xs mt-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        Fuga reprehenderit pariatur atque excepturi incidunt a
         dignissimos odio, repudiandae nulla laboriosam.
        
        </p>
    <Link href="/products">
    <button className="mt-4 text-xs bg-black text-white py-1 px-3 rounded">
      Conheça nossos produtos!
      </button>
    </Link>
      
    </main>
    <Footer />
    </>
  )
}

export default Home
