import type { NextPage } from "next";
import Head from "next/head";


const Home: NextPage = () => {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/faviacon.ico" />
    </Head>

    <main>
      <h1>Welcome to <a href="https://nextjs.org" target="_blank">Next.js!</a></h1>

      
    </main>
    
    </>
  )
}

export default Home
